window.HTCU_DATA = {
  range: { start: 1960, end: 1975, initialYear: 1969 },
  media: {
    freedomMae: { type:'image', src:'https://commons.wikimedia.org/wiki/Special:Redirect/file/MaeFrancesMoultrie1961.png', sourcePage:'https://commons.wikimedia.org/wiki/File:MaeFrancesMoultrie1961.png', credit:'Federal Bureau of Investigation / Wikimedia Commons', rights:'Public domain in the United States' },
    stonewall1969: { type:'image', src:'https://commons.wikimedia.org/wiki/Special:Redirect/file/LgStonewall%201969.jpg', sourcePage:'https://commons.wikimedia.org/wiki/File:LgStonewall_1969.jpg', credit:'National Park Service / Wikimedia Commons', rights:'Public domain, U.S. National Park Service' },
    apollo11: { type:'video', src:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Apollo%2011%20Moonwalk%20Montage.webm', poster:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Apollo%2011%20video%20after%20moonwalk.jpg', sourcePage:'https://commons.wikimedia.org/wiki/File:Apollo_11_Moonwalk_Montage.webm', credit:'NASA Johnson / Wikimedia Commons', rights:'Public domain, NASA' },
    nixonFarewell: { type:'image', src:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Nixon%20farewell.jpg', sourcePage:'https://commons.wikimedia.org/wiki/File:Nixon_farewell.jpg', credit:'White House Photo Office / Nixon Presidential Library / Wikimedia Commons', rights:'Public domain, U.S. federal government' },
    nixonAudio: { type:'audio', src:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Nixon%20resignation%20audio%20with%20buzz%20removed.ogg', sourcePage:'https://commons.wikimedia.org/wiki/File:Nixon_resignation_audio_with_buzz_removed.ogg', credit:'Richard Nixon / Miller Center / Wikimedia Commons', rights:'Public domain in the United States' },
    oldMainNow: { type:'image', src:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Old%20Main%20at%20Sunset%20%2820472170850%29.jpg', sourcePage:'https://commons.wikimedia.org/wiki/File:Old_Main_at_Sunset_(20472170850).jpg', credit:'Casey A. Cass / CU Boulder / Wikimedia Commons', rights:'CC0 1.0' }
  },
  moments: [
    {
      id:'m1961', year:1961.45, label:'1961', shortTitle:'Freedom Rides / Charles Biggers', portal:'ride', title:'A CU student enters the Freedom Rides', dek:'A national campaign against segregated interstate travel becomes part of CU history through Charles Biggers, then returns to Boulder with him.', sourceLabel:'Direct participation',
      chapters:[
        { id:'departure', kind:'image', media:'freedomMae', kicker:'May 1961 · United States', title:'The road is the argument.', body:['The Freedom Riders travelled through the South to test whether interstate travel facilities would comply with federal desegregation rulings. Movement itself became political: where riders sat, which facilities they entered, and whether federal law would be enforced.'], sourceName:'National Park Service — Freedom Riders National Monument', sourceUrl:'https://www.nps.gov/places/freedom-riders-national-monument.htm' },
        { id:'biggers', kind:'text-field', kicker:'CU Boulder · 1961', title:'Charles Biggers joins the rides.', body:['CU Boulder identifies student Charles Biggers as Boulder’s first Freedom Rider. He joined the campaign and was arrested in Jackson, Mississippi after refusing to leave a whites-only waiting room.'], fragments:['CORE TRAINING','JACKSON, MISSISSIPPI','CU STUDENT','FREEDOM RIDER'], sourceName:'CU Boulder 150 — Student Life Through the Decades', sourceUrl:'https://www.colorado.edu/today/2026/03/13/student-life-through-decades' },
        { id:'return', kind:'return', kicker:'July 3, 1961 · Norlin Library', title:'The history comes back to campus.', body:['Biggers later spoke in front of Norlin Library. This is the clearest direct relation in the prototype: CU is not simply observing a distant national event. A CU student participates in it and returns with the experience.'], fragments:['NORLIN LIBRARY','JULY 3','1961','BOULDER'], sourceName:'CU Boulder 150 — Student Life Through the Decades', sourceUrl:'https://www.colorado.edu/today/2026/03/13/student-life-through-decades' },
        { id:'limits', kind:'sources', kicker:'What survives', title:'The archive is uneven.', body:['The prototype can show the wider event through reusable federal imagery and can document Biggers through CU’s historical account. It does not invent an image of Biggers or pretend that every part of the relation is equally visible.'] }
      ]
    },
    {
      id:'m1969', year:1969.55, label:'1969', shortTitle:'Stonewall / Apollo 11 / campus change', portal:'simultaneity', title:'1969 does not have one centre', dek:'Stonewall, Apollo 11 and institutional change at CU occupy the same months without collapsing into a single historical story.', sourceLabel:'Dense simultaneity',
      chapters:[
        { id:'field', kind:'split-media', media:'stonewall1969', media2:'apollo11', kicker:'June–July 1969', title:'Two images of the same summer.', body:['Within three weeks, the Stonewall uprising and the first crewed lunar landing become globally legible events. Their proximity in time does not make them one narrative. The interface keeps both active at once.'] },
        { id:'stonewall', kind:'image', media:'stonewall1969', kicker:'June 28, 1969 · New York City', title:'Stonewall.', body:['Resistance following a police raid on the Stonewall Inn became a major reference point in the modern movement for gay and lesbian civil rights.'], sourceName:'National Park Service — Stonewall National Monument', sourceUrl:'https://www.nps.gov/ston/learn/index.htm' },
        { id:'apollo', kind:'video', media:'apollo11', kicker:'July 20–21, 1969', title:'At the same time, another live image enters history.', body:['Apollo 11 lands on the Moon. Television makes the event a mass-mediated planetary spectacle, watched by an enormous international audience.'], sourceName:'NASA — Apollo 11 Mission Overview', sourceUrl:'https://www.nasa.gov/history/apollo-11-mission-overview/' },
        { id:'campus', kind:'text-field', kicker:'CU Boulder · 1969', title:'The university is changing in other directions.', body:['At CU, the Hayakawa confrontation at Macky, the emergence of UMAS, and Black Studies taking institutional form belong to the same year without becoming effects of Stonewall or Apollo 11.'], fragments:['MACKY','UMAS','BLACK STUDIES','STUDENT POWER','RECRUITMENT','RETENTION'], sourceName:'CU Coloradan — A Change is Gonna Come', sourceUrl:'https://www.colorado.edu/coloradan/2010/09/01/change-gonna-come' },
        { id:'plural', kind:'sources', kicker:'One year, several histories', title:'The density is the point.', body:['At close scale, the system does not select one event as the representative meaning of 1969. Scientific, political, institutional and social histories remain simultaneous and differently related to CU.'] }
      ]
    },
    {
      id:'m1970', year:1970.84, label:'1970', shortTitle:'Boulder Gay Liberation', portal:'network', title:'A movement becomes a place to meet', dek:'Boulder Gay Liberation forms in November 1970 and gradually acquires rooms, publications, dances, services and institutional support.', sourceLabel:'Movement becomes local',
      chapters:[
        { id:'formation', kind:'text-field', kicker:'November 1970 · Boulder', title:'First, people meet in private homes.', body:['CU’s archival description dates the formation of Boulder Gay Liberation to November 1970. The group begins as a social and political organization rather than as a single spectacular event.'], fragments:['NOVEMBER 1970','PRIVATE HOMES','BOULDER','GAY LIBERATION'], sourceName:'CU Digital Library — Boulder Gay Liberation Collection', sourceUrl:'https://cudl.colorado.edu/luna/servlet/CUB~42~42' },
        { id:'infrastructure', kind:'network', kicker:'1970–1972 · Boulder / CU', title:'A movement accumulates infrastructure.', body:['The group develops social spaces, publications, counselling and resource services, political activity, coffeehouse meetings and dances. It also acquires CU student-government support and an office in the UMC.'], fragments:['OFFICE','UMC','COFFEEHOUSE','DANCES','COUNSELLING','PUBLICATIONS','POLITICAL WORK','LIBRARY'] },
        { id:'publications', kind:'publication-field', kicker:'Boulder Gay Record · Gayly Planet', title:'The archive is full of voices, but not all of it is ours to copy.', body:['The collection includes local and national publications, newspaper clippings, fliers and posters. CU Libraries notes that rights are unclear for some items, so the prototype names and links them without turning uncertain scans into decoration.'], fragments:['BOULDER GAY RECORD','GAYLY PLANET','FLIERS','POSTERS','NEWSPAPER CLIPPINGS'], sourceName:'CU Digital Library — Boulder Gay Liberation Collection', sourceUrl:'https://cudl.colorado.edu/luna/servlet/CUB~42~42' },
        { id:'recovery', kind:'present-image', media:'oldMainNow', kicker:'CU Boulder · archival recovery', title:'The collection becomes visible again.', body:['Students and Libraries staff later organized the collection, made it searchable and used it in teaching and exhibition work. The campus image here is deliberately contemporary: it marks where this history is being recovered now, not what Boulder looked like in 1970.'], sourceName:'CU Libraries — Students preserve and celebrate LGBTQ+ activism', sourceUrl:'https://libraries.colorado.edu/2023/06/07/students-preserve-and-celebrate-lgbtq-activism-new-collection-and-exhibition' },
        { id:'relation', kind:'sources', kicker:'From national movement to local form', title:'Transmission is not a straight line.', body:['Stonewall is part of the historical field from which gay liberation movements emerge, but Boulder’s organization has its own actors, local conditions and institutional history.'] }
      ]
    },
    {
      id:'m1974', year:1974.50, label:'1974', shortTitle:'Los Seis / Watergate', portal:'counterpoint', title:'Two crises occupy the same year', dek:'Los Seis de Boulder and Nixon’s resignation are placed in one temporal field while the interface refuses to make either explain the other.', sourceLabel:'Contemporaneity without causality',
      chapters:[
        { id:'los-seis', kind:'names', kicker:'May 27–29, 1974 · Boulder', title:'Los Seis de Boulder.', names:['Neva Romero','Una Jaakola','Reyes Martínez','Florencio Granado','Heriberto Terán','Francisco Dougherty'], body:['Six activists involved in El Movimiento died in two incidents in Boulder. CU Libraries documents their movement involvement and CU affiliations while also preserving uncertainty about key circumstances.'], sourceName:'CU Libraries — Remembering Los Seis de Boulder', sourceUrl:'https://libraries.colorado.edu/2024/05/13/remembering-los-seis-de-boulder-through-education-and-preservation' },
        { id:'unknown', kind:'absence', kicker:'The record does not close', title:'Unknown is part of the historical record.', body:['The project does not reconstruct the incidents, assign an unproven causal story, or replace uncertainty with a plausible image. The absence of resolution is displayed as such.'], fragments:['KNOWN','ARCHIVED','DISPUTED','UNKNOWN'] },
        { id:'archive', kind:'archive-field', kicker:'CU / Boulder archives', title:'What remains is distributed.', body:['Relevant material includes El Diario de la Gente, UMAS records, official records and later archival and memorial work. The history survives across documents, institutions, memories and public space rather than in one authoritative object.'], fragments:['EL DIARIO DE LA GENTE','UMAS 1968–1974','OFFICIAL RECORDS','ORAL HISTORY','MEMORIALS'], sourceName:'CU Libraries — Remembering Los Seis de Boulder', sourceUrl:'https://libraries.colorado.edu/2024/05/13/remembering-los-seis-de-boulder-through-education-and-preservation' },
        { id:'nixon', kind:'audio-image', media:'nixonFarewell', audio:'nixonAudio', kicker:'August 8–9, 1974 · Washington, D.C.', title:'Months later, Nixon resigns.', body:['After the Watergate crisis and under threat of impeachment, Richard Nixon announces his resignation and leaves office on August 9, becoming the first U.S. president to resign.'], sourceName:'National Archives — Nixon and Watergate', sourceUrl:'https://www.archives.gov/exhibits/american_originals/nixon.html' },
        { id:'counterpoint', kind:'sources', kicker:'Why put them together?', title:'Because history is simultaneous before it is explanatory.', body:['Los Seis and Watergate belong to different political histories. Their juxtaposition demonstrates one of the project’s central rules: sharing a year can be historically revealing without becoming a claim of causation.'] }
      ]
    }
  ]
};
